In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
ruta = "/content/drive/MyDrive/excels/indicadores-de-personas-departamentos-2022-corregida.xlsx"
df_censo = pd.read_excel(ruta)

df_censo.head()

,dpto,p_total,p_a17,p_0a3,p_4a5,p_6a12,p_13a17,p_18a,p_18a29,p_30a54,...,p1425,CODPROV,PROV,CODDPTO,DPTO_1,Departamentos_poblacion_total,Departamentos_hogares_total,Departamentos_latitud_centroide,Departamentos_longitud_centroide,Departamentos_superficie_km2
0,2007,221001,41264,7447,4772,17398,11647,179737,45844,80762,...,38669,2,Ciudad Autónoma de Buenos Aires,2007,Comuna 1,221001,106509,-34.606380,-58.371723,17.762647
1,2014,160609,21941,4277,2339,8758,6567,138668,37173,52382,...,30279,2,Ciudad Autónoma de Buenos Aires,2014,Comuna 2,160609,83818,-34.585157,-58.394234,6.603693
2,2021,193537,33045,5550,3668,13857,9970,160492,36826,72103,...,31360,2,Ciudad Autónoma de Buenos Aires,2021,Comuna 3,193537,92555,-34.613830,-58.402686,6.386384
3,2028,227024,51932,8225,5618,22520,15569,175092,40351,81064,...,39123,2,Ciudad Autónoma de Buenos Aires,2028,Comuna 4,227024,91186,-34.642423,-58.388728,21.971238
4,2035,192449,30914,5111,3337,13029,9437,161535,31569,73861,...,27174,2,Ciudad Autónoma de Buenos Aires,2035,Comuna 5,192449,93208,-34.617359,-58.420608,6.660252

Utilizamos *df.censohead()* para inspeccionnar donde empiezan mis datos

In [ ]:
#df.head()
#df.tail()
#df.info()
#df.describe()
#df.isnull().sum()
#df.duplicated().sum()

In [ ]:
df_censo.tail()

,dpto,p_total,p_a17,p_0a3,p_4a5,p_6a12,p_13a17,p_18a,p_18a29,p_30a54,...,p1425,CODPROV,PROV,CODDPTO,DPTO_1,Departamentos_poblacion_total,Departamentos_hogares_total,Departamentos_latitud_centroide,Departamentos_longitud_centroide,Departamentos_superficie_km2
522,90112,23438,7069,1413,772,2854,2030,16369,5220,6951,...,5234,90,Tucumán,90112,Trancas,23438,6922,-26.343406,-65.405827,3015.821803
523,90119,102589,28580,5241,3179,11860,8300,74009,19722,35003,...,20447,90,Tucumán,90119,Yerba Buena,102589,29624,-26.786382,-65.344722,158.203221
524,94008,98922,28196,4794,3293,11816,8293,70726,18500,36550,...,18177,94,"Tierra del Fuego, Antártida e Islas del Atlánt...",94008,Río Grande,98922,34738,-53.747675,-68.134659,6585.793160
525,94011,6027,1956,362,219,832,543,4071,1190,2065,...,1160,94,"Tierra del Fuego, Antártida e Islas del Atlánt...",94011,Tolhuin,6027,2215,-54.425160,-67.502465,6419.918882
526,94015,80009,21270,3659,2476,8898,6237,58739,14597,31156,...,13682,94,"Tierra del Fuego, Antártida e Islas del Atlánt...",94015,Ushuaia,80009,29234,-54.769567,-66.682787,7681.087001

*df_censo.tail()*,    para observar donde terminan

In [ ]:
df_censo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 527 entries, 0 to 526
Data columns (total 68 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   dpto                              527 non-null    int64
 1   p_total                           527 non-null    int64
 2   p_a17                             527 non-null    int64
 3   p_0a3                             527 non-null    int64
 4   p_4a5                             527 non-null    int64
 5   p_6a12                            527 non-null    int64
 6   p_13a17                           527 non-null    int64
 7   p_18a                             527 non-null    int64
 8   p_18a29                           527 non-null    int64
 9   p_30a54                           527 non-null    int64
 10  p_55a69                           527 non-null    int64
 11  p_70a                             527 non-null    int64
 12  m_total                           527 non-null    int64
 13  m_a17                             527 non-null    int64
 14  m_0a3                             527 non-null    int64
 15  m_4a5                             527 non-null    int64
 16  m_6a12                            527 non-null    int64
 17  m_13a17                           527 non-null    int64
 18  m_18a                             527 non-null    int64
 19  m_18a29                           527 non-null    int64
 20  m_30a54                           527 non-null    int64
 21  m_55a69                           527 non-null    int64
 22  m_70a                             527 non-null    int64
 23  v_total                           527 non-null    int64
 24  v_a17                             527 non-null    int64
 25  v_0a3                             527 non-null    int64
 26  v_4a5                             527 non-null    int64
 27  v_6a12                            527 non-null    int64
 28  v_13a17                           527 non-null    int64
 29  v_18a                             527 non-null    int64
 30  v_18a29                           527 non-null    int64
 31  v_30a54                           527 non-null    int64
 32  v_55a69                           527 non-null    int64
 33  v_70a                             527 non-null    int64
 34  p0a3_asiste                       527 non-null    int64
 35  p_cobertura_123                   527 non-null    int64
 36  p_cobertura_4                     527 non-null    int64
 37  p_cobertura_5                     527 non-null    int64
 38  p65_jubilacion                    527 non-null    int64
 39  p65_pension                       527 non-null    int64
 40  p65_jubilacion_o_pension          527 non-null    int64
 41  p_pension_no_contrib              527 non-null    int64
 42  p65_total                         527 non-null    int64
 43  p18a_sin_instruccion              527 non-null    int64
 44  p18a_primaria                     527 non-null    int64
 45  p18a_secundaria                   527 non-null    int64
 46  p18a_soloprimaria                 527 non-null    int64
 47  p18a_solosecundaria               527 non-null    int64
 48  p18a_terciaria                    527 non-null    int64
 49  p18a_universitaria                527 non-null    int64
 50  p4a5_asiste                       527 non-null    int64
 51  p6a12_asiste                      527 non-null    int64
 52  p1317_asiste                      527 non-null    int64
 53  p1317_sin_secundaria              527 non-null    int64
 54  p1829_asiste                      527 non-null    int64
 55  p1829_sin_secundaria              527 non-null    int64
 56  p1425_asiste                      527 non-null    int64
 57  p1425_sin_secundaria              527 non-null    int64
 58  p1425                             527 non-null    int64
 59  CODPROV                           527 non-null    int64
 60  PROV                              527 non-null    object
 61  CODDPTO                           527 non-null    int64
 62  DPTO_1                            527 non-null    object
 63  Departamentos_poblacion_total     527 non-null    int64
 64  Departamentos_hogares_total       527 non-null    int64
 65  Departamentos_latitud_centroide   527 non-null    float64
 66  Departamentos_longitud_centroide  527 non-null    float64
 67  Departamentos_superficie_km2      527 non-null    float64
dtypes: float64(3), int64(63), object(2)
memory usage: 280.1+ KB

*df_censo.info()*, para conocer la informacion de mis columnas y averiguar si hay datos nulos

In [ ]:
df_censo.describe()

,dpto,p_total,p_a17,p_0a3,p_4a5,p_6a12,p_13a17,p_18a,p_18a29,p_30a54,...,p1425_asiste,p1425_sin_secundaria,p1425,CODPROV,CODDPTO,Departamentos_poblacion_total,Departamentos_hogares_total,Departamentos_latitud_centroide,Departamentos_longitud_centroide,Departamentos_superficie_km2
count,527.000000,5.270000e+02,527.000000,527.000000,527.000000,527.000000,527.000000,5.270000e+02,527.000000,527.000000,...,527.000000,527.000000,527.000000,527.000000,527.000000,5.270000e+02,527.000000,527.000000,527.000000,527.000000
mean,36664.055028,8.656316e+04,23157.316888,4147.094877,2546.637571,9683.246679,6780.337761,6.340585e+04,16100.641366,29192.757116,...,6237.662239,9258.853890,16121.516129,36.497154,36664.055028,8.656042e+04,30231.094877,-32.536044,-62.824493,5275.924552
std,28847.588635,1.635606e+05,43158.886355,7740.652982,4743.466542,18150.893726,12547.045122,1.208945e+05,31216.103553,55997.672028,...,11460.487231,16660.262124,30685.503741,28.950520,28847.588635,1.635609e+05,57252.565066,5.437117,4.106762,6701.887894
min,2007.000000,4.130000e+02,98.000000,22.000000,10.000000,46.000000,19.000000,2.980000e+02,53.000000,146.000000,...,18.000000,35.000000,59.000000,2.000000,2007.000000,4.130000e+02,179.000000,-54.769567,-72.065992,6.386384
25%,6761.500000,1.279100e+04,3660.000000,673.000000,409.500000,1542.000000,1050.500000,8.968000e+03,2319.000000,4116.500000,...,968.000000,1487.000000,2362.000000,6.000000,6761.500000,1.279100e+04,4475.000000,-35.553863,-65.844777,1350.486415
50%,30049.000000,3.207700e+04,9299.000000,1702.000000,1017.000000,3785.000000,2748.000000,2.244600e+04,5834.000000,10133.000000,...,2452.000000,3942.000000,6114.000000,30.000000,30049.000000,3.207700e+04,10508.000000,-32.706069,-62.733185,3120.434081
75%,62038.500000,8.724900e+04,25024.500000,4524.500000,2688.000000,10434.000000,7191.000000,6.284250e+04,16101.500000,29000.500000,...,6369.500000,9877.500000,16651.000000,62.000000,62038.500000,8.724900e+04,28331.000000,-27.994385,-59.028014,6140.690323
max,94015.000000,1.837168e+06,534500.000000,97926.000000,59108.000000,225872.000000,151594.000000,1.302668e+06,343412.000000,624669.000000,...,135092.000000,198634.000000,346353.000000,94.000000,94015.000000,1.837168e+06,576586.000000,-22.137631,-53.960529,63073.440701

In [ ]:
#armo una lista con los  codigos de departamentos del amba
amba_departamentos = [
    2007, 2014, 2021, 2028, 2035, 2042, 2049, 2056, 2063, 2070,
    2077, 2084, 2091, 2098, 2105,
    6028, 6035, 6091, 6098, 6119, 6126, 6134, 6245, 6252, 6260,
    6270, 6274, 6329, 6364, 6371, 6408, 6410, 6412, 6427, 6434,
    6441, 6490, 6497, 6515, 6525, 6539, 6560, 6568, 6638, 6648,
    6658, 6749, 6756, 6760, 6778, 6805, 6840, 6861
]

Dado que la investigación se centra en los departamentos y comunas que integran el Área Metropolitana de Buenos Aires (AMBA), se filtró el dataset original conservando únicamente las observaciones correspondientes a dicha región.

In [ ]:
print(df_censo["CODDPTO"].dtype)
print(df_censo["CODDPTO"].head())

int64
0    2007
1    2014
2    2021
3    2028
4    2035
Name: CODDPTO, dtype: int64

Antes de realizar cualquier filtrado, es necesario inspeccionar la estructura de la columna `CODDPTO` (código de departamento).

In [ ]:
df_censo_amba = df_censo[df_censo["CODDPTO"].isin(amba_departamentos)]
df_censo_amba.head()
##Utilizamos el método .isin() de Pandas. Esta función es más eficiente para escribir múltiples condiciones
# Al pasar nuestra lista `amba_departamentos` como argumento, Pandas  selecciona solo las filas que coinciden con nuestros códigos de interés.
# Este nuevo DataFrame (`df_censo_amba`) será la base para todos nuestros cálculos estadísticos posteriores.

,dpto,p_total,p_a17,p_0a3,p_4a5,p_6a12,p_13a17,p_18a,p_18a29,p_30a54,...,p1425,CODPROV,PROV,CODDPTO,DPTO_1,Departamentos_poblacion_total,Departamentos_hogares_total,Departamentos_latitud_centroide,Departamentos_longitud_centroide,Departamentos_superficie_km2
0,2007,221001,41264,7447,4772,17398,11647,179737,45844,80762,...,38669,2,Ciudad Autónoma de Buenos Aires,2007,Comuna 1,221001,106509,-34.606380,-58.371723,17.762647
1,2014,160609,21941,4277,2339,8758,6567,138668,37173,52382,...,30279,2,Ciudad Autónoma de Buenos Aires,2014,Comuna 2,160609,83818,-34.585157,-58.394234,6.603693
2,2021,193537,33045,5550,3668,13857,9970,160492,36826,72103,...,31360,2,Ciudad Autónoma de Buenos Aires,2021,Comuna 3,193537,92555,-34.613830,-58.402686,6.386384
3,2028,227024,51932,8225,5618,22520,15569,175092,40351,81064,...,39123,2,Ciudad Autónoma de Buenos Aires,2028,Comuna 4,227024,91186,-34.642423,-58.388728,21.971238
4,2035,192449,30914,5111,3337,13029,9437,161535,31569,73861,...,27174,2,Ciudad Autónoma de Buenos Aires,2035,Comuna 5,192449,93208,-34.617359,-58.420608,6.660252

Finalmente aplico los filtros para obtener unicamente informacion de los departamentos del amba

In [ ]:
df_censo_amba.tail()

,dpto,p_total,p_a17,p_0a3,p_4a5,p_6a12,p_13a17,p_18a,p_18a29,p_30a54,...,p1425,CODPROV,PROV,CODDPTO,DPTO_1,Departamentos_poblacion_total,Departamentos_hogares_total,Departamentos_latitud_centroide,Departamentos_longitud_centroide,Departamentos_superficie_km2
131,6760,327650,87315,15185,9567,37035,25528,240335,63253,111699,...,61718,6,Buenos Aires,6760,San Miguel,327650,109322,-34.552324,-58.691515,83.707208
134,6778,97929,33146,6103,3756,14032,9255,64783,18115,32579,...,19655,6,Buenos Aires,6778,San Vicente,97929,30825,-35.070504,-58.431989,656.372966
138,6805,446291,122457,20040,12571,51961,37885,323834,80855,156218,...,85553,6,Buenos Aires,6805,Tigre,446291,147150,-34.381707,-58.598898,397.104367
143,6840,362319,79678,12779,8387,33616,24896,282641,60965,126729,...,60076,6,Buenos Aires,6840,Tres de Febrero,362319,136658,-34.596301,-58.578757,45.704398
146,6861,280541,55166,9131,5762,22610,17663,225375,39771,98769,...,41177,6,Buenos Aires,6861,Vicente López,280541,114743,-34.526803,-58.504436,34.808813

In [ ]:
df_censo_amba.info()

<class 'pandas.core.frame.DataFrame'>
Index: 53 entries, 0 to 146
Data columns (total 68 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   dpto                              53 non-null     int64
 1   p_total                           53 non-null     int64
 2   p_a17                             53 non-null     int64
 3   p_0a3                             53 non-null     int64
 4   p_4a5                             53 non-null     int64
 5   p_6a12                            53 non-null     int64
 6   p_13a17                           53 non-null     int64
 7   p_18a                             53 non-null     int64
 8   p_18a29                           53 non-null     int64
 9   p_30a54                           53 non-null     int64
 10  p_55a69                           53 non-null     int64
 11  p_70a                             53 non-null     int64
 12  m_total                           53 non-null     int64
 13  m_a17                             53 non-null     int64
 14  m_0a3                             53 non-null     int64
 15  m_4a5                             53 non-null     int64
 16  m_6a12                            53 non-null     int64
 17  m_13a17                           53 non-null     int64
 18  m_18a                             53 non-null     int64
 19  m_18a29                           53 non-null     int64
 20  m_30a54                           53 non-null     int64
 21  m_55a69                           53 non-null     int64
 22  m_70a                             53 non-null     int64
 23  v_total                           53 non-null     int64
 24  v_a17                             53 non-null     int64
 25  v_0a3                             53 non-null     int64
 26  v_4a5                             53 non-null     int64
 27  v_6a12                            53 non-null     int64
 28  v_13a17                           53 non-null     int64
 29  v_18a                             53 non-null     int64
 30  v_18a29                           53 non-null     int64
 31  v_30a54                           53 non-null     int64
 32  v_55a69                           53 non-null     int64
 33  v_70a                             53 non-null     int64
 34  p0a3_asiste                       53 non-null     int64
 35  p_cobertura_123                   53 non-null     int64
 36  p_cobertura_4                     53 non-null     int64
 37  p_cobertura_5                     53 non-null     int64
 38  p65_jubilacion                    53 non-null     int64
 39  p65_pension                       53 non-null     int64
 40  p65_jubilacion_o_pension          53 non-null     int64
 41  p_pension_no_contrib              53 non-null     int64
 42  p65_total                         53 non-null     int64
 43  p18a_sin_instruccion              53 non-null     int64
 44  p18a_primaria                     53 non-null     int64
 45  p18a_secundaria                   53 non-null     int64
 46  p18a_soloprimaria                 53 non-null     int64
 47  p18a_solosecundaria               53 non-null     int64
 48  p18a_terciaria                    53 non-null     int64
 49  p18a_universitaria                53 non-null     int64
 50  p4a5_asiste                       53 non-null     int64
 51  p6a12_asiste                      53 non-null     int64
 52  p1317_asiste                      53 non-null     int64
 53  p1317_sin_secundaria              53 non-null     int64
 54  p1829_asiste                      53 non-null     int64
 55  p1829_sin_secundaria              53 non-null     int64
 56  p1425_asiste                      53 non-null     int64
 57  p1425_sin_secundaria              53 non-null     int64
 58  p1425                             53 non-null     int64
 59  CODPROV                           53 non-null     int64
 60  PROV                              53 non-null     object
 61  CODDPTO                           53 non-null     int64
 62  DPTO_1                            53 non-null     object
 63  Departamentos_poblacion_total     53 non-null     int64
 64  Departamentos_hogares_total       53 non-null     int64
 65  Departamentos_latitud_centroide   53 non-null     float64
 66  Departamentos_longitud_centroide  53 non-null     float64
 67  Departamentos_superficie_km2      53 non-null     float64
dtypes: float64(3), int64(63), object(2)
memory usage: 28.6+ KB

In [ ]:
#Creo una copia de "df_censo_amba" para que los cambios no afecten al dataset principal
df_censo_amba = df_censo[df_censo["CODDPTO"].isin(amba_departamentos)].copy()

In [ ]:
#porcentaje de personas con estudios universitarios completos sobre el total de población de 18 años o más.
df_censo_amba["pct_universitarios"] = df_censo_amba["p18a_universitaria"] / df_censo_amba["p_18a"] * 100

#porcentaje de personas cuyo máximo nivel educativo alcanzado corresponde a la educación secundaria completa
df_censo_amba["pct_solosecundaria"] = df_censo_amba["p18a_solosecundaria"] / df_censo_amba["p_18a"] * 100
#porcentaje de personas cuyo maximo nivel educativo alcanzado fue primario y sin instruccionn formal.
df_censo_amba["pct_baja_educacion"]=(df_censo_amba["p18a_sin_instruccion"] + df_censo_amba["p18a_soloprimaria"]) /df_censo_amba["p_18a"] * 100

Las variables originales contienen cantidades absolutas de personas según nivel educativo. Para permitir comparaciones entre departamentos con poblaciones de distinto tamaño, se construyeron indicadores porcentuales utilizando como denominador la población de 18 años o más.

Se construyó un indicador de baja educación sumando las personas sin instrucción formal y aquellas cuyo máximo nivel alcanzado corresponde a la educación primaria.

In [ ]:
df_censo_amba.head()

,dpto,p_total,p_a17,p_0a3,p_4a5,p_6a12,p_13a17,p_18a,p_18a29,p_30a54,...,CODDPTO,DPTO_1,Departamentos_poblacion_total,Departamentos_hogares_total,Departamentos_latitud_centroide,Departamentos_longitud_centroide,Departamentos_superficie_km2,pct_universitarios,pct_solosecundaria,pct_baja_educacion
0,2007,221001,41264,7447,4772,17398,11647,179737,45844,80762,...,2007,Comuna 1,221001,106509,-34.606380,-58.371723,17.762647,22.130669,44.474427,25.524516
1,2014,160609,21941,4277,2339,8758,6567,138668,37173,52382,...,2014,Comuna 2,160609,83818,-34.585157,-58.394234,6.603693,39.363804,42.067384,9.840050
2,2021,193537,33045,5550,3668,13857,9970,160492,36826,72103,...,2021,Comuna 3,193537,92555,-34.613830,-58.402686,6.386384,19.641477,47.217307,23.745109
3,2028,227024,51932,8225,5618,22520,15569,175092,40351,81064,...,2028,Comuna 4,227024,91186,-34.642423,-58.388728,21.971238,11.585338,43.353209,37.065657
4,2035,192449,30914,5111,3337,13029,9437,161535,31569,73861,...,2035,Comuna 5,192449,93208,-34.617359,-58.420608,6.660252,24.823722,45.254589,19.145077

In [ ]:
#Filtramos los indices que realmente vamos a utilizar para nuestro proyecto
educacion_final = df_censo_amba[[
    "CODDPTO",
    "DPTO_1",
    "p_total",
    "p_18a",
    "pct_universitarios",
    "pct_solosecundaria",
    "pct_baja_educacion"
]]

In [ ]:
educacion_final.head(40)

,CODDPTO,DPTO_1,p_total,p_18a,pct_universitarios,pct_solosecundaria,pct_baja_educacion
0,2007,Comuna 1,221001,179737,22.130669,44.474427,25.524516
1,2014,Comuna 2,160609,138668,39.363804,42.067384,9.840050
2,2021,Comuna 3,193537,160492,19.641477,47.217307,23.745109
3,2028,Comuna 4,227024,175092,11.585338,43.353209,37.065657
4,2035,Comuna 5,192449,161535,24.823722,45.254589,19.145077
5,2042,Comuna 6,201764,168561,30.937761,42.547802,15.104324
6,2049,Comuna 7,213262,172542,20.199140,44.950215,24.232361
7,2056,Comuna 8,203888,148624,5.088007,40.765960,48.260712
8,2063,Comuna 9,167908,133580,12.465189,45.811499,31.784698
9,2070,Comuna 10,171896,140187,17.757709,46.562092,23.868832
10,2077,Comuna 11,201905,166228,23.032822,45.284790,19.931059
11,2084,Comuna 12,235364,194100,27.885626,42.941783,17.329727
12,2091,Comuna 13,262330,219265,38.712061,38.956970,11.473787
13,2098,Comuna 14,247252,211461,40.325166,39.476783,10.805302
14,2105,Comuna 15,195265,161655,25.159754,43.949151,19.954224
18,6028,Almirante Brown,583209,422869,5.060669,40.617071,48.170947
19,6035,Avellaneda,366117,279418,8.099335,43.749866,40.262975
27,6091,Berazategui,358328,261399,6.283115,42.849055,44.267193
28,6098,Berisso,100685,73096,6.726770,44.583835,40.003557
31,6119,Brandsen,32350,22834,7.488832,37.904003,45.165105
32,6126,Campana,107976,78213,9.008733,42.326723,41.659315
33,6134,Cañuelas,70542,48475,6.003094,38.646725,48.781846
49,6245,Ensenada,63978,45776,6.357043,44.060206,42.067896
50,6252,Escobar,256071,180663,8.696855,40.402296,44.376546
51,6260,Esteban Echeverría,337880,240577,5.499694,40.815622,48.175013
53,6270,Ezeiza,198620,138248,4.610555,41.477634,48.388403
54,6274,Florencio Varela,488103,335207,2.774405,37.993538,55.143240
63,6329,General Las Heras,17980,12930,6.836814,40.208817,42.335654
68,6364,General Rodríguez,142315,93973,4.642823,38.087536,52.265012
69,6371,General San Martín,444503,339021,7.201619,42.008017,43.589925
74,6408,Hurlingham,185361,140963,6.486099,42.799174,44.335748
75,6410,Ituzaingó,177983,136244,10.349814,45.242359,36.273157
76,6412,José C. Paz,326527,226073,2.825636,37.076520,55.952281
79,6427,La Matanza,1837168,1302668,4.166142,40.779385,50.040225
80,6434,Lanús,460081,354375,7.789771,42.387302,42.092981
81,6441,La Plata,756074,571484,16.703530,45.427169,29.359002
89,6490,Lomas de Zamora,685644,503421,7.815526,40.333637,45.378520
90,6497,Luján,110111,80791,9.733757,40.299043,41.504623
93,6515,Malvinas Argentinas,349401,254029,3.948368,40.369800,51.053226
95,6525,Marcos Paz,64761,44240,4.674503,35.556058,52.264919

Finalmente esta es la tabla con la informacion con la que se va unificar el dataset principal