<a href="https://colab.research.google.com/github/tost1n/Tp-laboratorio/blob/main/Tp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sympy as sp
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [6]:
DF=pd.read_csv('/content/Empleo-AMBA (2).csv')

/tmp/ipykernel_4259/1613573358.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  DF=pd.read_csv('/content/Empleo-AMBA (2).csv')

In [4]:
DF.head()

,LINK,provincia_id,departamento_id,clae2,letra,Cantidad_trabajadores,Cantidad_trabajadores_Hombres,Cantidad_trabajadores_Mujeres,Remuneracion_media,Remuneracion_media_Hombres,Remuneracion_media_Mujeres,Remuneracion_mediana,Remuneracion_mediana_Hombres,Remuneracion_mediana_Mujeres,Poblacion_radio,Viviendas_radio
0,1_10_12,2,2007,1.0,A,2,2.0,NaN,150000.0000,150000.000,NaN,150000.00,150000.000,NaN,584,606
1,1_10_12,2,2007,6.0,B,1,1.0,NaN,337377.8100,337377.810,NaN,337377.81,337377.810,NaN,584,606
2,1_10_12,2,2007,10.0,C,4,2.0,2.0,53289.2875,43690.815,62887.76,48271.49,43690.815,62887.76,584,606
3,1_10_12,2,2007,13.0,C,1,NaN,1.0,72176.2000,NaN,72176.20,72176.20,NaN,72176.20,584,606
4,1_10_12,2,2007,21.0,C,1,1.0,NaN,373915.9500,373915.950,NaN,373915.95,373915.950,NaN,584,606

In [5]:
DF.tail()

,LINK,provincia_id,departamento_id,clae2,letra,Cantidad_trabajadores,Cantidad_trabajadores_Hombres,Cantidad_trabajadores_Mujeres,Remuneracion_media,Remuneracion_media_Hombres,Remuneracion_media_Mujeres,Remuneracion_mediana,Remuneracion_mediana_Hombres,Remuneracion_mediana_Mujeres,Poblacion_radio,Viviendas_radio
508984,68613310,6,6861,84.0,O,16,6.0,10.0,209554.436875,454433.251667,62627.148000,69575.290,186903.265,51658.81,1022,392
508985,68613310,6,6861,85.0,P,20,5.0,15.0,140988.221500,142675.562000,140425.774667,117515.380,127509.610,107521.15,1022,392
508986,68613310,6,6861,86.0,Q,7,2.0,5.0,165429.368571,103643.960000,190143.532000,104359.000,103643.960,104359.00,1022,392
508987,68613310,6,6861,91.0,R,1,NaN,1.0,137147.570000,NaN,137147.570000,137147.570,NaN,137147.57,1022,392
508988,68613310,6,6861,94.0,S,4,3.0,1.0,114986.142500,97687.203333,166882.960000,127855.085,125019.960,166882.96,1022,392

In [ ]:
DF.dtypes

In [ ]:
DF.describe()

In [7]:
#Consultamos si tiene datos faltantes
DF.isnull().sum()

LINK                                  0
provincia_id                          0
departamento_id                       0
clae2                                68
letra                                68
Cantidad_trabajadores                 0
Cantidad_trabajadores_Hombres     87988
Cantidad_trabajadores_Mujeres    235036
Remuneracion_media                    0
Remuneracion_media_Hombres        87988
Remuneracion_media_Mujeres       235036
Remuneracion_mediana                  0
Remuneracion_mediana_Hombres      87988
Remuneracion_mediana_Mujeres     235036
Poblacion_radio                       0
Viviendas_radio                       0
dtype: int64

In [8]:
#Borramos los datos nulos que interpretamos como faltantes
print(f"Forma del dataframe antes de borrar las filas con nulos: {DF.shape}")

# Borrar filas si "clae2" o "letra" son nulos
DF_limpio = DF.dropna(subset=["clae2", "letra"])

print(f"Forma del dataframe despues de borrar las filas con nulos: {DF_limpio.shape}")
DF_limpio

Forma del dataframe antes de borrar las filas con nulos: (508989, 16)
Forma del dataframe despues de borrar las filas con nulos: (508921, 16)

,LINK,provincia_id,departamento_id,clae2,letra,Cantidad_trabajadores,Cantidad_trabajadores_Hombres,Cantidad_trabajadores_Mujeres,Remuneracion_media,Remuneracion_media_Hombres,Remuneracion_media_Mujeres,Remuneracion_mediana,Remuneracion_mediana_Hombres,Remuneracion_mediana_Mujeres,Poblacion_radio,Viviendas_radio
0,1_10_12,2,2007,1.0,A,2,2.0,NaN,150000.000000,150000.000000,NaN,150000.000,150000.000,NaN,584,606
1,1_10_12,2,2007,6.0,B,1,1.0,NaN,337377.810000,337377.810000,NaN,337377.810,337377.810,NaN,584,606
2,1_10_12,2,2007,10.0,C,4,2.0,2.0,53289.287500,43690.815000,62887.760000,48271.490,43690.815,62887.76,584,606
3,1_10_12,2,2007,13.0,C,1,NaN,1.0,72176.200000,NaN,72176.200000,72176.200,NaN,72176.20,584,606
4,1_10_12,2,2007,21.0,C,1,1.0,NaN,373915.950000,373915.950000,NaN,373915.950,373915.950,NaN,584,606
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
508984,68613310,6,6861,84.0,O,16,6.0,10.0,209554.436875,454433.251667,62627.148000,69575.290,186903.265,51658.81,1022,392
508985,68613310,6,6861,85.0,P,20,5.0,15.0,140988.221500,142675.562000,140425.774667,117515.380,127509.610,107521.15,1022,392
508986,68613310,6,6861,86.0,Q,7,2.0,5.0,165429.368571,103643.960000,190143.532000,104359.000,103643.960,104359.00,1022,392
508987,68613310,6,6861,91.0,R,1,NaN,1.0,137147.570000,NaN,137147.570000,137147.570,NaN,137147.57,1022,392
508988,68613310,6,6861,94.0,S,4,3.0,1.0,114986.142500,97687.203333,166882.960000,127855.085,125019.960,166882.96,1022,392

In [9]:
#Interpretamos los datos nulos en ciertas columnas como valor 0 y lo cambiamos para poder analizarlos como un numero
columnas_con_nulos = ["Cantidad_trabajadores_Hombres", "Cantidad_trabajadores_Mujeres", "Remuneracion_media_Hombres", "Remuneracion_media_Mujeres", "Remuneracion_mediana_Hombres", "Remuneracion_mediana_Mujeres"]
DF_limpio[columnas_con_nulos] = DF_limpio[columnas_con_nulos].fillna(0)
DF_limpio

/tmp/ipykernel_4259/160433440.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF_limpio[columnas_con_nulos] = DF_limpio[columnas_con_nulos].fillna(0)

,LINK,provincia_id,departamento_id,clae2,letra,Cantidad_trabajadores,Cantidad_trabajadores_Hombres,Cantidad_trabajadores_Mujeres,Remuneracion_media,Remuneracion_media_Hombres,Remuneracion_media_Mujeres,Remuneracion_mediana,Remuneracion_mediana_Hombres,Remuneracion_mediana_Mujeres,Poblacion_radio,Viviendas_radio
0,1_10_12,2,2007,1.0,A,2,2.0,0.0,150000.000000,150000.000000,0.000000,150000.000,150000.000,0.00,584,606
1,1_10_12,2,2007,6.0,B,1,1.0,0.0,337377.810000,337377.810000,0.000000,337377.810,337377.810,0.00,584,606
2,1_10_12,2,2007,10.0,C,4,2.0,2.0,53289.287500,43690.815000,62887.760000,48271.490,43690.815,62887.76,584,606
3,1_10_12,2,2007,13.0,C,1,0.0,1.0,72176.200000,0.000000,72176.200000,72176.200,0.000,72176.20,584,606
4,1_10_12,2,2007,21.0,C,1,1.0,0.0,373915.950000,373915.950000,0.000000,373915.950,373915.950,0.00,584,606
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
508984,68613310,6,6861,84.0,O,16,6.0,10.0,209554.436875,454433.251667,62627.148000,69575.290,186903.265,51658.81,1022,392
508985,68613310,6,6861,85.0,P,20,5.0,15.0,140988.221500,142675.562000,140425.774667,117515.380,127509.610,107521.15,1022,392
508986,68613310,6,6861,86.0,Q,7,2.0,5.0,165429.368571,103643.960000,190143.532000,104359.000,103643.960,104359.00,1022,392
508987,68613310,6,6861,91.0,R,1,0.0,1.0,137147.570000,0.000000,137147.570000,137147.570,0.000,137147.57,1022,392
508988,68613310,6,6861,94.0,S,4,3.0,1.0,114986.142500,97687.203333,166882.960000,127855.085,125019.960,166882.96,1022,392

In [10]:
# Verificamos los cambios
DF_limpio.isnull().sum()

LINK                             0
provincia_id                     0
departamento_id                  0
clae2                            0
letra                            0
Cantidad_trabajadores            0
Cantidad_trabajadores_Hombres    0
Cantidad_trabajadores_Mujeres    0
Remuneracion_media               0
Remuneracion_media_Hombres       0
Remuneracion_media_Mujeres       0
Remuneracion_mediana             0
Remuneracion_mediana_Hombres     0
Remuneracion_mediana_Mujeres     0
Poblacion_radio                  0
Viviendas_radio                  0
dtype: int64

In [11]:
# Contamos el número de filas duplicadas
duplicadas = DF_limpio.duplicated().sum()
print(f"Número de filas duplicadas: {duplicadas}")

Número de filas duplicadas: 0